### ISSUE TITLE
Target packets to specific address

### ISSUE THREAD

**Issue by fsedarkalex** [Victoare/SR-WLED-audio-server-win#2]
Hi!

Thanks for this tool! In my case all my smart home appliances are residing in a VLAN seperated by a firewall.

Would it be possible to add a configuration where the tool sends packets to?
I guess currently it is hardcoded as 255.255.255.255 (global broadcast).

I would like to input a custom address (which could then be either a network broadcast or a specific IP of the respective WLED node)

**Comment by fsedarkalex** [comment]
Okay forget what I said... I just noticed that it is actually multicast, not broadcast.
I was able to set up the UDB Multicast repeater function using the MC-address 239.0.0.1

**Comment by Victoare** [comment]
Heyo! 
Happy to hear that there is a a solution. 
This cross VLAN unicast repeating will probably be usefull to a couple people.
If someone will try to find a solution for that, can you describe what router/firewall are you using and what is needed to set this up?

**Comment by fsedarkalex** [comment]
I am using Opnsense as firewall. The feature is called "UDB Broadcast Relay" and might be available for other firewall as well - unfortunately this will likely not work with consumer boxed routers lige fritz boxes.

![image](https://github.com/Victoare/SR-WLED-audio-server-win/assets/16449266/9e03f9d0-8ad0-4656-b818-c3e9def3ab65)

In my case I am using a different port, because we have multiple independant WLED setups here.

**Comment by Victoare** [comment]
Thanks!
